language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
before_install:
  - 'export GO111MODULE=on'
  - 'go get -v golang.org/x/lint/golint'
  - 'go get -v github.com/kisielk/errcheck'
  - 'go get -v golang.org/x/tools/cmd/cover'
  - 'go get -v github.com/mattn/goveralls'
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0


script:
  - 'go mod tidy'
  - 'go test -v -covermode=atomic -coverprofile=coverage.out -race'
  - 'goveralls -coverprofile=coverage.out -service=travis-ci'
